### ISSUE TITLE
add a link to get out of the settings

### ISSUE THREAD

**Issue by aelisya** [Arlodotexe/UWP-Companion#10]
**BUG**
When I go into the settings I can no longer get out without closing the popup and reopen it

**Idea to solve the problem**
Add a button to return to the first "page" of the extensions

**Screenshot of the problem**
There is no way to go out of this screen.
![No way to go out of this screen](https://cdn.discordapp.com/attachments/534038175471894528/594876543319146499/Annotation_2019-06-30_150420.png)

**Comment by Arlodotexe** [comment]
To close the settings page, click the Settings icon again

**Comment by aelisya** [comment]
How did I not notice this ... ><'
