### ISSUE TITLE
Chrome webstore results in 404

### ISSUE THREAD

**Issue by Bluscream** [Arlodotexe/UWP-Companion#4]
https://chrome.google.com/webstore/detail/uwp-companion-beta

Can you upload the crx to https://github.com/Arlodotexe/UWP-Companion/releases ?

**Comment by paulelms** [comment]
Still 404 after closing issue. Here is the working link: https://chrome.google.com/webstore/detail/uwp-companion-beta/egfgdliklfgpmdjfofbmhmoejdhehani?hl=ru
